### PR TITLE
prettify ✨

### PR DESCRIPTION
**Pull request by andrewkmin**
$title

### CODE REVIEW

**Comment by r-n-o** [comment]
Looks good besides the merge conflicts to resolve :)

**Comment by andrewkmin** [comment]
> Looks good besides the merge conflicts to resolve :)

resolved!

**Review by r-n-o — COMMENTED** [review]
We might want to exclude `noble-ed25519.js` and `noble-hashes.js` from the list of linted files: they're vendored in.

**Review by r-n-o — APPROVED** [review]
Other than that though: looks good, only whitespace changes, so no reason to block 👍

**Pull request merged**
